#pragma checksum "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BA4EC907C51DCD1F075B0385CC90500144DBF66C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ShoreKeeper.Host.Wpf {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 29 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PortTextBox;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StartButton;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StopButton;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RecordButton;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StopRecordButton;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TranscribeButton;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecordingStatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecordingsFolderTextBlock;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TranscriptTextBox;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox MessagesListBox;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LogsTextBox;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SendButton;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MessageTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ShoreKeeper.Host.Wpf;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.PortTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.StartButton = ((System.Windows.Controls.Button)(target));
            
            #line 30 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.StartButton.Click += new System.Windows.RoutedEventHandler(this.StartButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.StopButton = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.StopButton.Click += new System.Windows.RoutedEventHandler(this.StopButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.StatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.RecordButton = ((System.Windows.Controls.Button)(target));
            
            #line 50 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.RecordButton.Click += new System.Windows.RoutedEventHandler(this.RecordButton_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.StopRecordButton = ((System.Windows.Controls.Button)(target));
            
            #line 51 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.StopRecordButton.Click += new System.Windows.RoutedEventHandler(this.StopRecordButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TranscribeButton = ((System.Windows.Controls.Button)(target));
            
            #line 52 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.TranscribeButton.Click += new System.Windows.RoutedEventHandler(this.TranscribeButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.RecordingStatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.RecordingsFolderTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.TranscriptTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.MessagesListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            case 12:
            
            #line 76 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearLogsButton_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.LogsTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.SendButton = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.SendButton.Click += new System.Windows.RoutedEventHandler(this.SendButton_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.MessageTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 85 "..\..\..\..\ShoreKeeperHost\ShoreKeeper.Host.Wpf\ShoreKeeper.Host.Wpf\MainWindow.xaml"
            this.MessageTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.MessageTextBox_KeyDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

